exports.initialProducts = [
  {
    name: "Classic Cotton Shirt",
    description: "Classic formal shirt made from 100% premium cotton with perfect fit. Breathable fabric suitable for office and meetings.",
    category: "shirt",
    brand: "StyleCraft",
    price: 1299,
    originalPrice: 1899,
    image: "shirt3.webp",
    rating: 4.8,
    reviewCount: 128,
    stock: 15,
    discount: 31,
    isFeatured: true
  },
  {
    name: "Sports Shoes",
    description: "Lightweight and comfortable sports shoes perfect for daily running, gym, and sports activities. Shock-absorbing sole.",
    category: "shoes",
    brand: "WalkFlex",
    price: 999,
    originalPrice: 1399,
    image: "shoes2.webp",
    rating: 4.5,
    reviewCount: 92,
    stock: 20,
    discount: 28,
    isFeatured: true
  },
  {
    name: "Slim Fit Jeans",
    description: "Comfortable stretch denim jeans with modern slim fit design. Highly durable and styled for a casual day out.",
    category: "jeans",
    brand: "DenimPro",
    price: 1499,
    originalPrice: 1999,
    image: "jeans3.webp",
    rating: 4.7,
    reviewCount: 156,
    stock: 12,
    discount: 25,
    isFeatured: true
  },
  {
    name: "Leather Wallet",
    description: "Elegant and compact bi-fold wallet crafted from premium genuine leather. Features multiple card slots and secure cash compartment.",
    category: "accessories",
    brand: "LeatherCraft",
    price: 799,
    originalPrice: 1199,
    image: "wallet.webp",
    rating: 4.3,
    reviewCount: 84,
    stock: 25,
    discount: 33,
    isFeatured: true
  },
  {
    name: "Polo T-Shirt",
    description: "Soft cotton polo with classic collar design for everyday comfort and premium smart-casual look.",
    category: "tshirt",
    brand: "StyleCraft",
    price: 1199,
    originalPrice: 1599,
    image: "polotshirt.webp",
    rating: 4.6,
    reviewCount: 112,
    stock: 18,
    discount: 25,
    isFeatured: true
  },
  {
    name: "Formal Trousers",
    description: "Tailored fit trousers crafted with premium blend fabric, offering high comfort and sharp professional look.",
    category: "trousers",
    brand: "OfficePro",
    price: 1399,
    originalPrice: 1899,
    image: "trouser2.jpg",
    rating: 4.4,
    reviewCount: 68,
    stock: 10,
    discount: 26,
    isFeatured: true
  },
  {
    name: "Business Blazer",
    description: "Classic tailoring details meet modern styling in this slim-fit blazer. Perfect for formal board meetings or upscale evening events.",
    category: "jacket",
    brand: "OfficePro",
    price: 3299,
    originalPrice: 4999,
    image: "jacket.png",
    rating: 4.9,
    reviewCount: 45,
    stock: 8,
    discount: 34,
    isFeatured: true
  },
  {
    name: "Sports Cap",
    description: "Adjustable classic baseball cap designed with mesh back panel for ventilation. Ideal for outdoor workouts and casual styles.",
    category: "accessories",
    brand: "WalkFlex",
    price: 399,
    originalPrice: 599,
    image: "cap.png",
    rating: 4.1,
    reviewCount: 37,
    stock: 30,
    discount: 33,
    isFeatured: false
  },
  {
    name: "Casual T-Shirt",
    description: "Basic crew neck t-shirt made of super soft ring-spun cotton. Your daily wear essential.",
    category: "tshirt",
    brand: "StyleCraft",
    price: 499,
    originalPrice: 799,
    image: "tshirt.png",
    rating: 4.2,
    reviewCount: 215,
    stock: 50,
    discount: 37,
    isFeatured: false
  },
  {
    name: "Classic Analog Watch",
    description: "Timeless analog watch featuring quartz movement, leather strap, and minimal clean dial. Fits both formal and casual settings.",
    category: "accessories",
    brand: "WalkFlex",
    price: 1999,
    originalPrice: 2999,
    image: "watch.png",
    rating: 4.7,
    reviewCount: 73,
    stock: 14,
    discount: 33,
    isFeatured: true
  },
  {
    name: "Comfort Underwear",
    description: "Pack of comfortable stretch cotton trunks. Elasticated waistband and support panels designed for maximum daily comfort.",
    category: "underwear",
    brand: "StyleCraft",
    price: 299,
    originalPrice: 499,
    image: "underwear.png",
    rating: 4.5,
    reviewCount: 99,
    stock: 40,
    discount: 40,
    isFeatured: false
  },
  {
    name: "Premium Cotton Shirt",
    description: "Beautifully structured cotton shirt with button-down collar. Elegant linen-cotton mix offering absolute breathability.",
    category: "shirt",
    brand: "StyleCraft",
    price: 1299,
    originalPrice: 1899,
    image: "shirt2.png",
    rating: 4.8,
    reviewCount: 142,
    stock: 16,
    discount: 31,
    isFeatured: true
  }
];
